### ISSUE TITLE
Consider removing broken versions from packagist

### ISSUE THREAD

**Issue by lazka** [web-token/jwt-framework#333]
All the 3.0.0 versions are considered as compatible with PHP 7.4 because they lack a php version restriction themselves. This results in a broken project because of the PHP 8 syntax when updating with some automated tools like dependabot, or renovate.

Please consider removing all the 3.0.0 versions from packagist.

Also, thank you for this nice library.

**Comment by Spomky** [comment]
Hi @lazka,

I have not noticed that; sorry for the incovenient.
In this case, I will add the correct PHP version on all sub-packages. THis should fix the issue.

**Comment by lazka** [comment]
No problem.

I don't think adding the version restrictions is enough, since the old versions are still available and installable. It might help to avoid similar problems with future updates though.

If yanking a version somehow isn't possible, then I can manually block all the packages to upgrade everywhere I use them, so personally that is fine too, but will not help anyone else with a similar problem :)

**Comment by Spomky** [comment]
It is well understood.
I've just pushed the v3.0.2 and removed v3.0.0 and 3.0.1 from packagist.
I don't  know if packagist will restore the deleted versions. If this is the case, I will remove the tags from the repositories.

**Comment by lazka** [comment]
All v3.0.0 and v3.0.1 versions are back on packagist now, as far as I see.

**Comment by Spomky** [comment]
correct... then I will remove those tags in all packages first.

**Comment by Spomky** [comment]
I deleted all tags in the sub-repositories and the main one.
I also removed them on packagist. They should be gone forever.
Let me know if you see something wrong after that.

**Comment by lazka** [comment]
Thanks!

Some packages still show as outdated re 3.0.1, but they wont upgrade because they depend on jwt-core which has correct PHP requirements. So I'm happy.

Off topic: I was just about to suggest that you change the default branch for the read-only repos since they "seem" abandoned, and that always threw me off. But I see you did that now :) :+1:
